### ISSUE TITLE
Remove node_modules

### ISSUE THREAD

**Issue by EliasPereyra** [EBEREGIT/Nodejs_CLI_app#1]
Hi eberegit, nice to meet you! 

I was reading your CLI CRUD app tutorial in the freeCodeCamp's blog and it's really good. I just wanted to make a suggestion, and it's to remove the _node_modules_ folder, because in the README.md you specifiy to install the dependencies with **npm i**, and it would not be necessary because when cloning the repo, the _node_modules_ will downloaded automatically. 

I know that there are not many dependencies, but it's a good practice to have a **.gitignore file**, or specifying that's not necessary to install with npm because the __node_modules__ is already in the repo.

Just wanted to make a little suggestion, and again, great tutorial!

**Comment by EBEREGIT** [comment]
Hi Elías,

Thank you for the observation. Will you like to create a PR for it?

**Comment by EliasPereyra** [comment]
Yes of course!
